version: "3.9"

services:
  cassandra:
    image: "docker.io/bitnami/cassandra:3-debian-10"
    ports:
      - "7000:7000"
      - "9042:9042"
    volumes:
      - "cassandra_data:/bitnami"
    environment:
      - CASSANDRA_SEEDS=cassandra
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_PASSWORD=cassandra
      # Inter-node cluster communication port. Default: 7000
      - CASSANDRA_TRANSPORT_PORT_NUMBER=7000
      # client port default 9042
      - CASSANDRA_CQL_PORT_NUMBER=9042

volumes:
  cassandra_data:
    driver: local
